"""users_to_courses

Revision ID: 740fd3889dc6
Revises: 9ebe51a1438b
Create Date: 2021-01-16 19:09:31.739870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '740fd3889dc6'
down_revision = '9ebe51a1438b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('fio', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('company', sa.String(length=128), nullable=True),
    sa.Column('position', sa.String(length=128), nullable=True),
    sa.Column('date_of_birth', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_User_role'), 'User', ['role'], unique=False)
    op.create_index(op.f('ix_User_username'), 'User', ['username'], unique=True)
    op.create_table('users_to_courses',
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['Course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], )
    )
    op.drop_index('ix_user_role', table_name='user')
    op.drop_index('ix_user_username', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('password', sa.VARCHAR(length=128), nullable=True),
    sa.Column('role', sa.VARCHAR(length=10), nullable=True),
    sa.Column('fio', sa.VARCHAR(length=128), nullable=True),
    sa.Column('company', sa.VARCHAR(length=128), nullable=True),
    sa.Column('date_of_birth', sa.VARCHAR(length=50), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('position', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_username', 'user', ['username'], unique=1)
    op.create_index('ix_user_role', 'user', ['role'], unique=False)
    op.drop_table('users_to_courses')
    op.drop_index(op.f('ix_User_username'), table_name='User')
    op.drop_index(op.f('ix_User_role'), table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###
