"""New columns in User_answer

Revision ID: 8e132af95a88
Revises: b0ae651b920e
Create Date: 2021-02-10 01:56:21.425268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e132af95a88'
down_revision = 'b0ae651b920e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User_answer', sa.Column('lesson_id', sa.Integer(), nullable=True))
    op.add_column('User_answer', sa.Column('lesson_name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User_answer', 'lesson_name')
    op.drop_column('User_answer', 'lesson_id')
    # ### end Alembic commands ###
