"""added new positions

Revision ID: 9ebe51a1438b
Revises: afd46bea877f
Create Date: 2021-01-13 20:04:24.770371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ebe51a1438b'
down_revision = 'afd46bea877f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('company', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('date_of_birth', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('phone_number', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('position', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'position')
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'date_of_birth')
    op.drop_column('user', 'company')
    # ### end Alembic commands ###
