"""added new column

Revision ID: a5274edef744
Revises: 4e7567f809e7
Create Date: 2021-01-23 13:32:53.962214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5274edef744'
down_revision = '4e7567f809e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons_to_courses', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons_to_courses', 'order')
    # ### end Alembic commands ###
