"""Новая колонка в Lesson

Revision ID: b0ae651b920e
Revises: 
Create Date: 2021-02-09 01:10:29.794108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0ae651b920e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Lesson', sa.Column('questions_to_pass', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Lesson', 'questions_to_pass')
    # ### end Alembic commands ###
